version: '3.8'
 
services:
  web:
    build: .
    ports:
      - "8090:80"  # Maps host port 8090 to container port 80
    volumes:
      - .:/usr/share/nginx/html  # Mounts current directory to serve files
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80